version: '3.1'
services:
  keycloak:
    image: jboss/keycloak:9.0.0
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
    ports:
    - "8080:8080"
    - "8443:8443"
    - "8787:8787"
    - "9990:9990"
    command:
    - "-b"
    - "0.0.0.0"
    - "--debug *:8787"
  post_process:
    build: .
    image: borisskert/keycloak-tool:latest
    depends_on:
    - keycloak
    links:
    - keycloak
    volumes:
    - ./example-config:/tmp/keycloak-tool/configs
    environment:
    - KEYCLOAK_URL=http://keycloak:8080
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin123
    - WAIT_TIME_IN_SECONDS=120
    - SPRING_PROFILES_INCLUDE=debug
    - IMPORT_FORCE=false
    command: config-cli
