logging:
  level:
    com.github.borisskert.keycloak.config.service.RealmImportService: debug
    com.github.borisskert.keycloak.config.service.AuthenticationFlowsImportService: debug
    com.github.borisskert.keycloak.config.service.ExecutionFlowsImportService: debug
    com.github.borisskert.keycloak.config.service.RequiredActionsImportService: debug
    com.github.borisskert.keycloak.config.service.ComponentImportService: debug
    com.github.borisskert.keycloak.config.service.UserImportService: debug
    com.github.borisskert.keycloak.config.service.CustomImportService: debug
    com.github.borisskert.keycloak.config.service.RoleImportService: debug
    com.github.borisskert.keycloak.config.service.ClientImportService: debug
    com.github.borisskert.keycloak.config.service.ScopeMappingImportService: debug
    com.github.borisskert.keycloak.config.service.GroupImportService: debug
